name: 'setup Debian'
description: 'Setup a Debian container for running CI'
runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        apt-get update
        apt-get install --yes \
          build-essential \
          autoconf \
          automake \
          gcc-multilib \
          git \
          gtk-doc-tools \
          libssl-dev \
          liblzma-dev \
          libtool \
          libzstd-dev \
          linux-headers-generic \
          meson \
          rsync \
          scdoc \
          zlib1g-dev \
          zstd
