# SPDX-FileCopyrightText: 2024 Emil Velikov <emil.l.velikov@gmail.com>
# SPDX-FileCopyrightText: 2024 Lucas De Marchi <lucas.de.marchi@gmail.com>
#
# SPDX-License-Identifier: LGPL-2.1-or-later

name: 'setup Debian'
description: 'Setup a Debian container for running CI'
runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        apt-get update
        apt-get install --yes \
          autoconf \
          automake \
          build-essential \
          gcc-multilib \
          git \
          gtk-doc-tools \
          liblzma-dev \
          libssl-dev \
          libtool \
          libzstd-dev \
          linux-headers-generic \
          meson \
          scdoc \
          zlib1g-dev \
          zstd
