#  Copyright 2010 Lennart Poettering
#
# This file has been copied from systemd. It is a dirty trick to simplify
# compilation when CWD is not the root of the source tree. This file is not
# intended to be distributed.  So, don't touch it, even better ignore it!

all:
	$(MAKE) -C ..

clean:
	$(MAKE) -C .. clean

.PHONY: all clean
