# SPDX-FileCopyrightText: 2024 Emil Velikov <emil.l.velikov@gmail.com>
# SPDX-FileCopyrightText: 2024 Lucas De Marchi <lucas.de.marchi@gmail.com>
#
# SPDX-License-Identifier: LGPL-2.1-or-later

name: Build and Test

on:
  push:
    branches: [master, ci-test]
  pull_request:
    branches: [master]
  schedule:
    - cron: "30 2 * * 0"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - container: 'alpine:latest'
            meson_setup: '-Ddocs=false -Db_sanitize=none'
          - container: 'archlinux:multilib-devel'
            # fails on LD_PRELOAD
            skip_test_32: 'true'
          - container: 'debian:bullseye-slim'
            meson_setup: '-Dzstd=disabled -Dxz=disabled -Dzlib=disabled -Dopenssl=enabled -Dtools=true'
          - container: 'debian:unstable'
          - container: 'fedora:latest'
          - container: 'fedora:latest'
            meson_setup: '-Dxz=disabled -Ddlopen=all'
          - container: 'ubuntu:22.04'
          - container: 'ubuntu:22.04'
            meson_setup: '-Ddlopen=zstd,zlib'
          - container: 'ubuntu:24.04'

          # Special configurations

          # Variant with lld as linker
          - container: 'archlinux:multilib-devel'
            custom: 'ldd as linker'
            compiler: 'clang'
            linker: 'lld'
            skip: '32'

          # Variants with moduledir
          - container: 'archlinux:multilib-devel'
            meson_setup: '-Dmoduledir=/usr/lib/modules'
            custom: 'usr moduledir'
            compiler: 'gcc'
            skip: '32'
          - container: 'archlinux:multilib-devel'
            meson_setup: '-Dmoduledir=/kernel-modules'
            custom: 'custom moduledir'
            compiler: 'gcc'
            skip: '32'

    container:
      image: ${{ matrix.container }}

    steps:
      - name: Sparse checkout the local actions
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          sparse-checkout: .github
          path: local-actions

      - name: Setup OS
        uses: ./local-actions/.github/actions/setup-os

      - name: Cleanup local actions
        run: |
          rm -rf local-actions
          # The sparse checkout with REST API creates the current dir with the wrong
          # user. Tell git to just ignore.
          git config --global --add safe.directory '*'

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set the environment
        run: |
          .github/print-kdir.sh >> "$GITHUB_ENV"

      - name: configure checks
        run: |
          should_fail() {
            rm -rf build-setup-test/
            if meson setup "$@" build-setup-test/; then
              echo Command was expected to fail, but was successful
              return 1
            fi
          }
          should_pass() {
            rm -rf build-setup-test/
            meson setup "$@" build-setup-test/
          }

          should_fail -D distconfdir=relative/
          should_fail -D moduledir=relative/
          should_fail -D dlopen=nonexistent
          should_fail -D xz=disabled -D dlopen=xz

          should_pass -D dlopen=xz
          should_pass -D dlopen=xz -D xz=enabled

      - name: configure
        run: |
          setup_options="${{ matrix.meson_setup }}"

          if [[ -n "${{ matrix.linker }}" ]]; then
            export CC_LD="${{ matrix.linker }}"
          fi

          for compiler in gcc clang; do
          for bits in 32 64; do
            echo "::group::$compiler, $bits bit"

            if [[ -n "${{ matrix.custom }}" ]]; then
              builddir="builddir-$compiler-$bits-${{ matrix.custom }}/"
            else
              builddir="builddir-$compiler-$bits/"
            fi

            export CC="$compiler"
            if [[ "$bits" == "32" ]]; then
              export CC="$CC -m32"
              echo "::notice::TODO fix and reuse the original options."
              setup_options="$setup_options -Dzstd=disabled -Dxz=disabled -Dzlib=disabled -Dopenssl=disabled"
            fi

            if [[ -n "${{ matrix.compiler }}" && "${{ matrix.compiler }}" != "$compiler" ]]; then
              echo "::notice::Skipping combination with compiler $compiler"
            elif [[ "${{ matrix.skip }}" == "$bits" ]]; then
              echo "::notice::Combination annotated as SKIP."
            else
              meson setup --native-file build-dev.ini $setup_options "$builddir"
            fi

            echo "::endgroup::"
          done
          done


      - name: build
        run: |
          for compiler in gcc clang; do
          for bits in 32 64; do
            echo "::group::$compiler, $bits bit"

            if [[ -n "${{ matrix.custom }}" ]]; then
              builddir="builddir-$compiler-$bits-${{ matrix.custom }}/"
            else
              builddir="builddir-$compiler-$bits/"
            fi

            if [[ -n "${{ matrix.compiler }}" && "${{ matrix.compiler }}" != "$compiler" ]]; then
              echo "::notice::Skipping combination with compiler $compiler"
            elif [[ "${{ matrix.skip }}" == "$bits" ]]; then
              echo "::notice::Combination annotated as SKIP."
            else
              meson compile -C "$builddir"
            fi

            echo "::endgroup::"
          done
          done

      - name: test
        run: |
          for compiler in gcc clang; do
          for bits in 32 64; do
            echo "::group::$compiler, $bits bit"

            if [[ -n "${{ matrix.custom }}" ]]; then
              builddir="builddir-$compiler-$bits-${{ matrix.custom }}/"
            else
              builddir="builddir-$compiler-$bits/"
            fi

            if [[ -n "${{ matrix.compiler }}" && "${{ matrix.compiler }}" != "$compiler" ]]; then
              echo "::notice::Skipping combination with compiler $compiler"
            elif [[ "${{ matrix.skip }}" == "$bits" ]]; then
              echo "::notice::Combination annotated as SKIP."
            elif [[ "$bits" == "32" && "${{ matrix.skip_test_32 }}" == "true" ]]; then
                echo "::notice::TODO skipping failing tests."
            else
              meson test -C "$builddir" || meson test -C "$builddir" --verbose
            fi

            echo "::endgroup::"
          done
          done

      - name: install
        run: |
          for compiler in gcc clang; do
          for bits in 32 64; do
            echo "::group::$compiler, $bits bit"

            if [[ -n "${{ matrix.custom }}" ]]; then
              builddir="builddir-$compiler-$bits-${{ matrix.custom }}/"
            else
              builddir="builddir-$compiler-$bits/"
            fi

            if [[ -n "${{ matrix.compiler }}" && "${{ matrix.compiler }}" != "$compiler" ]]; then
              echo "::notice::Skipping combination with compiler $compiler"
            elif [[ "${{ matrix.skip }}" == "$bits" ]]; then
              echo "::notice::Combination annotated as SKIP."
            else
              DESTDIR=$PWD/inst meson install -C "$builddir"
            fi

            echo "::endgroup::"
          done
          done

      - name: distcheck
        run: |
          for compiler in gcc clang;
          for bits in 32 64; do
            echo "::group::$compiler, $bits bit"

            if [[ -n "${{ matrix.custom }}" ]]; then
              builddir="builddir-$compiler-$bits-${{ matrix.custom }}/"
            else
              builddir="builddir-$compiler-$bits/"
            fi

            if [[ -n "${{ matrix.compiler }}" && "${{ matrix.compiler }}" != "$compiler" ]]; then
              echo "::notice::Skipping combination with compiler $compiler"
            elif [[ "${{ matrix.skip }}" == "$bits" ]]; then
              echo "::notice::Combination annotated as SKIP."
            else
              meson dist -C "$builddir"
            fi

            echo "::endgroup::"
          done
          done
