# SPDX-FileCopyrightText: 2024 Emil Velikov <emil.l.velikov@gmail.com>
# SPDX-FileCopyrightText: 2024 Lucas De Marchi <lucas.de.marchi@gmail.com>
#
# SPDX-License-Identifier: LGPL-2.1-or-later

name: 'setup Archlinux'
description: 'Setup an Archlinux container for running CI'
runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        # Semi-regularly the packager key may have (temporarily) expired.
        # Somewhat robust solution is to wipe the local keyring and
        # regenerate/reinstall it prior to any other packages on the system.
        rm -rf /etc/pacman.d/gnupg
        pacman-key --init
        pacman-key --populate
        pacman --noconfirm -Sy archlinux-keyring

        pacman --noconfirm -Su \
          git \
          gtk-doc \
          linux-headers \
          meson \
          scdoc
