name: 'setup Archlinux'
description: 'Setup an Archlinux container for running CI'
runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        # Enable multilib, for building 32bit binaries
        echo -e '[multilib]\nInclude = /etc/pacman.d/mirrorlist' >> /etc/pacman.conf
        # Semi-regularly the packager key may have (temporarily) expired.
        # Somewhat robust solution is to wipe the local keyring and
        # regenerate/reinstall it prior to any other packages on the system.
        rm -rf /etc/pacman.d/gnupg
        pacman-key --init
        pacman-key --populate
        pacman --noconfirm -Sy archlinux-keyring

        pacman --noconfirm -Su \
          multilib-devel \
          linux-headers \
          meson \
          scdoc \
          git \
          gtk-doc
